security:
  url-rules:
    #    add Account
    - pattern: /user/add-account
      method: POST
      any-of-permissions:
        - Add Account

    - pattern: /owner/subuser/add-account/*
      method: POST
      any-of-permissions:
        - Add Account For Subowner

    - pattern: /admin/user/add-account/*
      method: POST
      any-of-permissions:
        - Add Account For Any User

    - pattern: /admin/subuser/add-account/*/*
      method: POST
      any-of-permissions:
        - Add Account For Any Owners Subowner



    #      modify account
    - pattern: /user/modify-account-details/*/*
      method: PUT
      any-of-permissions:
        - Modify Account Details

    - pattern: /owner/subuser/modify-account-details/*/*/*
      method: PUT
      any-of-permissions:
        - Modify Account Details For Subuser

    - pattern: /admin/user/modify-account-details/*/*/*
      method: PUT
      any-of-permissions:
        - Modify Account Details For Any User

    - pattern: /admin/subowner/modify-account-details/*/*/*/*
      method: PUT
      any-of-permissions:
        - Modify Account Details For Any Users Subuser


#Delete account

    - pattern: /user/delete-account/*/*
      method: DELETE
      any-of-permissions:
        - Delete Account

    - pattern: /owner/subuser/delete-account/*/*/*
      method: DELETE
      any-of-permissions:
        - Delete Subuser Account

    - pattern: /admin/user/delete-account/*/*/*
      method: DELETE
      any-of-permissions:
        - Delete Any User Account

    - pattern: /admin/subuser/delete-account/*/*/*/*
      method: DELETE
      any-of-permissions:
        - Delete Any Users Subuser Account

    #get account details

    - pattern: /user/get-account-detials/*/*
      method: GET
      any-of-permissions:
        - Get Own Account Details

    - pattern: /owner/subuser/get-account-detials/*/*/*
      method: GET
      any-of-permissions:
        - Get Subuser Account Details

    - pattern: /admin/user/get-account-detials/*/*/*
      method: GET
      any-of-permissions:
        - Get Any User Account Details

    - pattern: /admin/subuser/get-account-detials/*/*/*/*
      method: GET
      any-of-permissions:
        - Get Any Users Subuser Account Details


    #get all account details

    - pattern: /user/get-all-account-details
      method: GET
      any-of-permissions:
        - Get Own All Account Details

    - pattern: /owner/subuser/get-all-account-details/*
      method: GET
      any-of-permissions:
        - Get Subuser All Account Details

    - pattern: /admin/user/get-all-account-details/*
      method: GET
      any-of-permissions:
        - Get Any User All Account Details

    - pattern: /admin/subuser/get-all-account-details/*/*
      method: GET
      any-of-permissions:
        - Get Any Users Subuser All Account Details

#get methods all account details
    - pattern: /user/get-any-method-all-account-details/*
      method: GET
      any-of-permissions:
        - Get Own All Account Method Wise Details

    - pattern: /owner/subuser/get-any-method-all-account-details/*/*
      method: GET
      any-of-permissions:
        - Get Subuser All Account Method Wise Details

    - pattern: /admin/user/get-any-method-all-account-details/*/*
      method: GET
      any-of-permissions:
        - Get Any User All Account Method Wise Details

    - pattern: /admin/subuser/get-all-any-method-account-details/*/*/*
      method: GET
      any-of-permissions:
        - Get Any Users Subuser All Account Method Wise Details

