spring.application.name=expense_trancker


# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.jpa.properties.hibernate.format_sql=true

jwt.secretKey=laksjeoriujioanmcvkamspejoianscoka;mspoeu4(*@)#*!kjasd%*&&)(!@!!!$(2u98e2h3e9238uc982cm
jwt.expireationTime= 36000000


